### ISSUE TITLE
180 deg Reorientation (for screwdriver attachment) needs fine-tuning

### ISSUE THREAD

**Issue by yijiangh** [gramaziokohler/integral_timber_joints#110]
After smoothing, the reorientation movement still looks like this:
![image](https://user-images.githubusercontent.com/11905844/134616184-1a5c261c-a125-4b78-bd2c-1000669872cc.png)

I think here it's just that the end robot IK is sampled, and it's too far away from the start conf. We can either try turning this movement into a linear movement or be smarter about the sampling order.

**Comment by yijiangh** [comment]
@yck011522 I'd recommend turning the reorientation movements into linear movements, and we can see if it works out-of-the-box or not. Opinion?

**Comment by yck011522** [comment]
Worth giving it a try. @yijiangh 
Can do you a quick test form your side?

**Comment by yijiangh** [comment]
My quick test shows that it's definitely worth a try:
https://user-images.githubusercontent.com/11905844/135121353-9334e49e-8c08-49df-a153-3c8a031ab910.mp4

**Comment by yijiangh** [comment]
For 180-deg, it's possible but the z coordinate of the orient pose needs to be higher:

![image](https://user-images.githubusercontent.com/11905844/135134237-116cc5d4-f437-4957-92b4-e1f6b8269e1f.png)
![image](https://user-images.githubusercontent.com/11905844/135134278-a99a4770-12a8-4f60-ad7c-111051d452ca.png)

**Comment by yijiangh** [comment]
This is `A135_M1` of hypar:

![image](https://user-images.githubusercontent.com/11905844/135134780-453a2794-2886-4f2d-bd05-d3f3cb6bd49b.png)

**Comment by yijiangh** [comment]
Fixed by [237cf37](https://github.com/gramaziokohler/integral_timber_joints/commit/237cf379c3601e18cc03ebf461829df6fdd0585f)
