### ISSUE TITLE
Find a good home configuration for free motion planning

### ISSUE THREAD

**Issue by yijiangh** [gramaziokohler/integral_timber_joints#140]
In PDDLStream formulation, the planner can plan more efficiently if we can break the free motions into two segments - `start conf to home conf` and `home conf to end conf`. 

@yck011522 would you mind helping me find a good candidate?

**Comment by yck011522** [comment]
The current defined config seems to be an okay home position.

**Comment by yck011522** [comment]
@yijiangh I think the current initial config is fine for planning. Feel free to reopen issue if this is a problem.
