### ISSUE TITLE
Toolchanger offset causing collision with planned configurations

### ISSUE THREAD

**Issue by yijiangh** [gramaziokohler/integral_timber_joints#145]

**Comment by yijiangh** [comment]
- [ ] settle on a way we compare two frames (should specify point distance and  angle distance)
- [ ] settle on a way we compare two configurations (prismatic joint should have a different value than the revolute joint)
- [ ] why free motion's first trajectory point disagree with the given start_conf

**Comment by yck011522** [comment]
Joint Flip and Jump is pretty much the same thing, and both have the same limits:
0.05 meter and 10 degrees
