### ISSUE TITLE
Use tracIK for RFL IK (6+3) instead of the default pybullet IK

### ISSUE THREAD

**Issue by yijiangh** [gramaziokohler/integral_timber_joints#31]
We can use IKFast for 6-axis but we need diverse solutions for the RFL robot with `6+3` joints. 

Consider using https://bitbucket.org/traclabs/trac_ik/src/master/, but this needs a ROS instance running in a container. I am thinking about if there is a way to separate trac_ik from ROS. But I can start with the docker options, maybe the communication via rosbridge is bearable?

**Comment by yck011522** [comment]
@yijiangh Can we close this one, now that the IK seems to be fast enough? If one day you decide to continue to work on plotting tracIK to Windows, maybe we can reopen this?
