### ISSUE TITLE
Change the Beam Pickup flowchart for Pickup routine

### ISSUE THREAD

**Issue by yck011522** [gramaziokohler/integral_timber_joints#76]
The goal is to create a pickup station that can accomodate all different types of gripping scenarios.

Pickup routine for CLAMPED beams: (same as Fred's process)
1. robot picks up gripper
2. gripper comes in horizontally to pickup station
3. operator places beam into jaw horizontally
4. gripper jaw close
5. linear lift up

SCREWED_WITH_GRIPPER
1. Same as above
2. instead of lift up, it rotates to a top grasp pose
3. for each screwdriver, the operaor attach the screwdriver in (downward motion) to the beam

SCREWED_WITHOUT_GRIPPER
1. robot picks up the screwdriver that acts as a gripper.
2. screwdriver comes in horizontally to pickup station
3. operator places beam into the screw hole of screwdriver
4. operator press button on screwdriver to extend pin and lock
5. robot rotates to a top grasp pose similar to above
6. operator attaches the screwdriver in downward motion

**Comment by yijiangh** [comment]
Related to this collision scenario:

**Comment by yck011522** [comment]
New Movement to be implemented:

- PickScrewdriverFromStorageAction
- GenericGripperApproachBeamPickupAction
- CloseGripperOnBeamAction
- GenericFreeMoveBeamWithGripperAction

**Comment by yck011522** [comment]
**Pickup :**
![2021-09-10 16_53_29](https://user-images.githubusercontent.com/1297653/132873615-d00bb12f-820e-4f88-b132-c271ff49ea02.jpg)
**Pick up retracted: (Linear move)**
![2021-09-10 16_53_37](https://user-images.githubusercontent.com/1297653/132873566-4407d8b7-e7cb-4b45-8df5-16f248f9f478.jpg)
**Oriented (Free Move):**
![2021-09-10 16_53_39](https://user-images.githubusercontent.com/1297653/132873570-ecefbba6-b8c8-4ee6-a7f2-202ebb392e94.jpg)
**Attached more screwdrivers**
![2021-09-10 16_53_42](https://user-images.githubusercontent.com/1297653/132873730-092526dc-38f7-464e-abdc-2631bce5c4e2.jpg)

**Comment by yck011522** [comment]
![2021-09-10 18_42_52](https://user-images.githubusercontent.com/1297653/132888268-49c47dc4-ed51-429f-804d-ba911ebdbe4a.jpg)
